// Code generated by protoc-gen-go. DO NOT EDIT.
// source: actions.proto

package parser_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Action_Kind int32

const (
	Action_CONFIGURATION                 Action_Kind = 0
	Action_RUN_TIME_BEFORE_MATCH_ATTEMPT Action_Kind = 1
	Action_RUN_TIME_ONLY_IF_MATCH        Action_Kind = 2
)

var Action_Kind_name = map[int32]string{
	0: "CONFIGURATION",
	1: "RUN_TIME_BEFORE_MATCH_ATTEMPT",
	2: "RUN_TIME_ONLY_IF_MATCH",
}

var Action_Kind_value = map[string]int32{
	"CONFIGURATION":                 0,
	"RUN_TIME_BEFORE_MATCH_ATTEMPT": 1,
	"RUN_TIME_ONLY_IF_MATCH":        2,
}

func (x Action_Kind) String() string {
	return proto.EnumName(Action_Kind_name, int32(x))
}

func (Action_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{0, 0}
}

type SetVar_Operation int32

const (
	SetVar_SET_OPERATION               SetVar_Operation = 0
	SetVar_SUM_AND_SET_OPERATION       SetVar_Operation = 1
	SetVar_SUBSTRACT_AND_SET_OPERATION SetVar_Operation = 2
	SetVar_SET_TO_ONE_OPERATION        SetVar_Operation = 3
	SetVar_UNSET_OPERATION             SetVar_Operation = 4
)

var SetVar_Operation_name = map[int32]string{
	0: "SET_OPERATION",
	1: "SUM_AND_SET_OPERATION",
	2: "SUBSTRACT_AND_SET_OPERATION",
	3: "SET_TO_ONE_OPERATION",
	4: "UNSET_OPERATION",
}

var SetVar_Operation_value = map[string]int32{
	"SET_OPERATION":               0,
	"SUM_AND_SET_OPERATION":       1,
	"SUBSTRACT_AND_SET_OPERATION": 2,
	"SET_TO_ONE_OPERATION":        3,
	"UNSET_OPERATION":             4,
}

func (x SetVar_Operation) String() string {
	return proto.EnumName(SetVar_Operation_name, int32(x))
}

func (SetVar_Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{2, 0}
}

type Action struct {
	// Action's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Action's Parameter.
	Param string `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	// Action's kind
	// Reference: https://github.com/SpiderLabs/ModSecurity/blob/d5b93c1013ca9c9a96c75369576b54832e9a2b48/headers/modsecurity/actions/action.h#L120
	Kind                 Action_Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=parser.proto.Action_Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{0}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *Action) GetKind() Action_Kind {
	if m != nil {
		return m.Kind
	}
	return Action_CONFIGURATION
}

type ActionList struct {
	Item                 []*Action `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ActionList) Reset()         { *m = ActionList{} }
func (m *ActionList) String() string { return proto.CompactTextString(m) }
func (*ActionList) ProtoMessage()    {}
func (*ActionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{1}
}

func (m *ActionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionList.Unmarshal(m, b)
}
func (m *ActionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionList.Marshal(b, m, deterministic)
}
func (m *ActionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionList.Merge(m, src)
}
func (m *ActionList) XXX_Size() int {
	return xxx_messageInfo_ActionList.Size(m)
}
func (m *ActionList) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionList.DiscardUnknown(m)
}

var xxx_messageInfo_ActionList proto.InternalMessageInfo

func (m *ActionList) GetItem() []*Action {
	if m != nil {
		return m.Item
	}
	return nil
}

// Following is the derived class of Action.
type SetVar struct {
	// Information of Base class.
	Base *Action `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// SetVar's operation.
	// Reference: https://github.com/SpiderLabs/ModSecurity/blob/d5b93c1013ca9c9a96c75369576b54832e9a2b48/src/actions/set_var.h#L32
	Operation SetVar_Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=parser.proto.SetVar_Operation" json:"operation,omitempty"`
	// SetVar's variable.
	Variable             *Variable `protobuf:"bytes,3,opt,name=variable,proto3" json:"variable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetVar) Reset()         { *m = SetVar{} }
func (m *SetVar) String() string { return proto.CompactTextString(m) }
func (*SetVar) ProtoMessage()    {}
func (*SetVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{2}
}

func (m *SetVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVar.Unmarshal(m, b)
}
func (m *SetVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVar.Marshal(b, m, deterministic)
}
func (m *SetVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVar.Merge(m, src)
}
func (m *SetVar) XXX_Size() int {
	return xxx_messageInfo_SetVar.Size(m)
}
func (m *SetVar) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVar.DiscardUnknown(m)
}

var xxx_messageInfo_SetVar proto.InternalMessageInfo

func (m *SetVar) GetBase() *Action {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *SetVar) GetOperation() SetVar_Operation {
	if m != nil {
		return m.Operation
	}
	return SetVar_SET_OPERATION
}

func (m *SetVar) GetVariable() *Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

type LogData struct {
	// Information of Base class.
	Base *Action `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Content of LogData.
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogData) Reset()         { *m = LogData{} }
func (m *LogData) String() string { return proto.CompactTextString(m) }
func (*LogData) ProtoMessage()    {}
func (*LogData) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{3}
}

func (m *LogData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogData.Unmarshal(m, b)
}
func (m *LogData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogData.Marshal(b, m, deterministic)
}
func (m *LogData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogData.Merge(m, src)
}
func (m *LogData) XXX_Size() int {
	return xxx_messageInfo_LogData.Size(m)
}
func (m *LogData) XXX_DiscardUnknown() {
	xxx_messageInfo_LogData.DiscardUnknown(m)
}

var xxx_messageInfo_LogData proto.InternalMessageInfo

func (m *LogData) GetBase() *Action {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *LogData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Msg struct {
	Base                 *Action  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{4}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetBase() *Action {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Tag struct {
	Base                 *Action  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeb49063df94c2b8, []int{5}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetBase() *Action {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *Tag) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterEnum("parser.proto.Action_Kind", Action_Kind_name, Action_Kind_value)
	proto.RegisterEnum("parser.proto.SetVar_Operation", SetVar_Operation_name, SetVar_Operation_value)
	proto.RegisterType((*Action)(nil), "parser.proto.Action")
	proto.RegisterType((*ActionList)(nil), "parser.proto.ActionList")
	proto.RegisterType((*SetVar)(nil), "parser.proto.SetVar")
	proto.RegisterType((*LogData)(nil), "parser.proto.LogData")
	proto.RegisterType((*Msg)(nil), "parser.proto.Msg")
	proto.RegisterType((*Tag)(nil), "parser.proto.Tag")
}

func init() { proto.RegisterFile("actions.proto", fileDescriptor_eeb49063df94c2b8) }

var fileDescriptor_eeb49063df94c2b8 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x8f, 0x93, 0x40,
	0x14, 0xc6, 0x1d, 0xc0, 0xae, 0x7d, 0xeb, 0xee, 0xd6, 0xb1, 0x6e, 0xd8, 0x35, 0x6a, 0xe5, 0xc4,
	0x45, 0x0e, 0x98, 0x78, 0xf2, 0xc2, 0x76, 0xa9, 0x12, 0x0b, 0xb3, 0x19, 0x86, 0x8d, 0x9e, 0x26,
	0xd3, 0x96, 0x34, 0x44, 0x0b, 0x04, 0x26, 0xfe, 0x0f, 0xfe, 0x37, 0xde, 0xfd, 0xe7, 0x0c, 0x43,
	0x8b, 0x25, 0xa9, 0x87, 0x4d, 0x7a, 0xe3, 0xbd, 0xef, 0xf7, 0x7d, 0x0f, 0xbe, 0x00, 0x67, 0x62,
	0x29, 0xb3, 0x22, 0xaf, 0x9d, 0xb2, 0x2a, 0x64, 0x81, 0x9f, 0x96, 0xa2, 0xaa, 0xd3, 0xaa, 0x9d,
	0xae, 0x2f, 0x7e, 0x8a, 0x2a, 0x13, 0x8b, 0x1f, 0xe9, 0x56, 0xb6, 0xfe, 0x20, 0x18, 0x78, 0xca,
	0x80, 0x31, 0x18, 0xb9, 0xd8, 0xa4, 0x26, 0x9a, 0x20, 0x7b, 0x48, 0xd5, 0x33, 0x1e, 0xc3, 0xe3,
	0x52, 0x54, 0x62, 0x63, 0x6a, 0x6a, 0xd9, 0x0e, 0xf8, 0x1d, 0x18, 0xdf, 0xb3, 0x7c, 0x65, 0xea,
	0x13, 0x64, 0x9f, 0xbb, 0x57, 0xce, 0xfe, 0x09, 0xa7, 0x4d, 0x73, 0xbe, 0x64, 0xf9, 0x8a, 0x2a,
	0xcc, 0xfa, 0x0a, 0x46, 0x33, 0xe1, 0x67, 0x70, 0x36, 0x25, 0xd1, 0x2c, 0xf8, 0x94, 0x50, 0x8f,
	0x05, 0x24, 0x1a, 0x3d, 0xc2, 0x6f, 0xe1, 0x15, 0x4d, 0x22, 0xce, 0x82, 0xd0, 0xe7, 0x37, 0xfe,
	0x8c, 0x50, 0x9f, 0x87, 0x1e, 0x9b, 0x7e, 0xe6, 0x1e, 0x63, 0x7e, 0x78, 0xc7, 0x46, 0x08, 0x5f,
	0xc3, 0x65, 0x87, 0x90, 0x68, 0xfe, 0x8d, 0x07, 0xb3, 0x96, 0x19, 0x69, 0xd6, 0x07, 0x80, 0xf6,
	0xdc, 0x3c, 0xab, 0x25, 0xb6, 0xc1, 0xc8, 0x64, 0xba, 0x31, 0xd1, 0x44, 0xb7, 0x4f, 0xdd, 0xf1,
	0xa1, 0xd7, 0xa2, 0x8a, 0xb0, 0x7e, 0x6b, 0x30, 0x88, 0x53, 0x79, 0x2f, 0xaa, 0xc6, 0xb4, 0x10,
	0x75, 0xfb, 0xd5, 0xff, 0x35, 0x35, 0x04, 0xfe, 0x08, 0xc3, 0xa2, 0x4c, 0x2b, 0xd1, 0xac, 0x54,
	0x1f, 0xe7, 0xee, 0xeb, 0x3e, 0xde, 0x46, 0x3a, 0x64, 0x47, 0xd1, 0x7f, 0x06, 0xec, 0xc2, 0x93,
	0x5d, 0xf7, 0xaa, 0xb7, 0x53, 0xf7, 0xb2, 0x6f, 0xbe, 0xdf, 0xaa, 0xb4, 0xe3, 0xac, 0x5f, 0x08,
	0x86, 0x5d, 0x58, 0x53, 0x5f, 0xec, 0x33, 0x4e, 0xee, 0xfc, 0xae, 0xbe, 0x2b, 0x78, 0x11, 0x27,
	0x21, 0xf7, 0xa2, 0x5b, 0xde, 0x97, 0x10, 0x7e, 0x03, 0x2f, 0xe3, 0xe4, 0x26, 0x66, 0xd4, 0x9b,
	0xb2, 0x03, 0x80, 0x86, 0x4d, 0x18, 0x37, 0x2b, 0x46, 0x38, 0x89, 0xfc, 0x3d, 0x45, 0xc7, 0xcf,
	0xe1, 0x22, 0x89, 0xfa, 0xb8, 0x61, 0x85, 0x70, 0x32, 0x2f, 0xd6, 0xb7, 0x42, 0x8a, 0x07, 0x54,
	0x66, 0xc2, 0xc9, 0xb2, 0xc8, 0x65, 0x9a, 0xcb, 0xed, 0x0f, 0xb4, 0x1b, 0xad, 0x00, 0xf4, 0xb0,
	0x5e, 0x1f, 0x2b, 0x8a, 0x89, 0xa3, 0x44, 0x2d, 0x06, 0x8a, 0x7e, 0xff, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x33, 0xd4, 0xa4, 0x74, 0x44, 0x03, 0x00, 0x00,
}
